//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace community
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contributor
    {
        public string email { get; set; }
        public string name { get; set; }
        public bool admin { get; set; }
    }
}
