//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace community
{
    using System;
    using System.Collections.Generic;
    
    public partial class facebook_page
    {
        public facebook_page()
        {
            this.posts = new HashSet<post>();
        }
    
        public int id { get; set; }
        public int municipality_id { get; set; }
        public string url { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public string short_name { get; set; }
        public bool has_phone { get; set; }
        public bool has_email { get; set; }
        public bool has_about_page { get; set; }
        public string defined_location { get; set; }
        public string website { get; set; }
        public int milestones_count { get; set; }
        public int liked_pages { get; set; }
        public bool approved { get; set; }
        public string contributor_email { get; set; }
        public string facebook_id { get; set; }
        public Nullable<byte> type { get; set; }
    
        public virtual Municipality Municipality { get; set; }
        public virtual ICollection<post> posts { get; set; }
    }
}
