//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace community
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Social_PresenceEntities : DbContext
    {
        public Social_PresenceEntities()
            : base("name=Social_PresenceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<facebook_page> facebook_page { get; set; }
        public DbSet<Municipality> Municipalities { get; set; }
        public DbSet<post> posts { get; set; }
        public DbSet<Contributor> Contributors { get; set; }
    }
}
