//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace community
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipality
    {
        public Municipality()
        {
            this.facebook_page = new HashSet<facebook_page>();
        }
    
        public string name { get; set; }
        public int id { get; set; }
        public string country { get; set; }
        public Nullable<int> population { get; set; }
        public string state { get; set; }
        public string website { get; set; }
        public bool approved { get; set; }
    
        public virtual ICollection<facebook_page> facebook_page { get; set; }
    }
}
