//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace community
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime date { get; set; }
        public int likes { get; set; }
        public int mentions { get; set; }
        public string type { get; set; }
        public int length { get; set; }
        public bool contains_hashtags { get; set; }
        public bool has_responses { get; set; }
        public bool fan_post { get; set; }
        public int facebook_page_id { get; set; }
        public bool approved { get; set; }
    
        public virtual facebook_page facebook_page { get; set; }
    }
}
